package io.github.stream29.kodex.tool.imagegeneration

import de.infix.testBalloon.framework.core.testSuite

import io.github.stream29.kodex.agentstorage.cleanmodels.stable.StableImageGenerationResult
import io.github.stream29.kodex.agentstorage.cleanmodels.stable.StableImageGenerationToolEvent
import io.github.stream29.kodex.agentstorage.cleanmodels.unstable.PendingImageGenerationToolEvent
import io.github.stream29.kodex.openai.ImageData
import io.github.stream29.kodex.openai.ImageResponse
import io.github.stream29.kodex.openai.OpenAiResult
import io.github.stream29.kodex.openai.jsoncodec.OpenAiJsonCodec
import io.github.stream29.kodex.openai.ResponsesApiNamespace
import io.github.stream29.kodex.openai.client.test.mockOpenAiClient
import io.github.stream29.kodex.utils.kotlinxiocoroutines.SystemCoroutineFileSystem
import kotlinx.io.files.Path
import kotlinx.io.files.SystemTemporaryDirectory
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.io.encoding.Base64
import kotlin.random.Random
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertTrue



private val json = OpenAiJsonCodec

val imageGenerationToolsTest by testSuite {
    test("spec declares image gen namespace tool") {
        val namespace = ImageGenerationTools.spec as ResponsesApiNamespace
        val encoded = json.parseToJsonElement(json.encodeToString(namespace)).jsonObject
        val tool = encoded.getValue("tools").jsonArray.single().jsonObject

        assertEquals(ImageGenNamespace, encoded["name"]?.toString()?.trim('"'))
        assertEquals(ImageGenToolName, tool["name"]?.toString()?.trim('"'))
        assertEquals(
            """
            The `image_gen.imagegen` tool enables image generation from descriptions and editing of existing images based on specific instructions. Use it when:

            - The user requests an image based on a scene description, such as a diagram, portrait, comic, meme, or any other visual.
            - The user wants to modify an attached or previously generated image with specific changes, including adding or removing elements, altering colors, improving quality/resolution, or transforming the style (e.g., cartoon, oil painting).

            Guidelines:
            - In code mode, pass the result to `generatedImage(result)`.
            - Omit both `referenced_image_paths` and `num_last_images_to_include` when generating a brand new image.
            - For edits, use `referenced_image_paths` when every target image has a local file path.
            - If you have not seen a local image yet, use `view_image` to inspect it before editing.
            - Use `num_last_images_to_include` only when at least one target image has no local file path.
            - Set `num_last_images_to_include` to the smallest number of recent conversation images that includes every target image, up to 5.
            - Never provide both `referenced_image_paths` and `num_last_images_to_include`.
            - If neither mechanism can include every target image, ask the user to attach the missing images again.
            - Directly generate the image without reconfirmation or clarification unless required images must be attached again.
            - After each image generation, do not mention anything related to download. Do not summarize the image. Do not ask followup question. Do not say ANYTHING after you generate an image.
            - Always use this tool for image editing unless the user explicitly requests otherwise. Do not use the `python` tool for image editing unless specifically instructed.
            """.trimIndent() + "\n",
            tool.getValue("description").jsonPrimitive.content,
        )
        assertFalse("output_schema" in tool)
    }

    test("parameters expose prompt and edit inputs") {
        val namespace = ImageGenerationTools.spec as ResponsesApiNamespace
        val tool = namespace.tools.single()
        val encoded = json.parseToJsonElement(json.encodeToString(tool)).jsonObject
        val properties = encoded
            .getValue("parameters")
            .jsonObject
            .getValue("properties")
            .jsonObject

        assertTrue("prompt" in properties)
        assertTrue("referenced_image_paths" in properties)
        assertTrue("num_last_images_to_include" in properties)
        properties.values.forEach { property ->
            assertFalse("description" in property.jsonObject)
        }
    }

    test("generated bytes are returned as image content with the persisted path hint") {
        val root = Path(SystemTemporaryDirectory, "image-generation-tool-${Random.nextLong()}")
        val bytes = byteArrayOf(1, 2, 3)
        try {
            val encodedImage = Base64.encode(bytes)
            val tool = ImageGenerationTools.createTool(
                client = ImageGenerationToolClient(
                    client = mockOpenAiClient {
                        generateImage {
                            OpenAiResult.Success(
                                ImageResponse(
                                    created = 1,
                                    data = listOf(ImageData(encodedImage)),
                                ),
                            )
                        }
                    },
                ),
                outputDirectory = Path(root, "session"),
            )

            val completed = assertIs<StableImageGenerationToolEvent>(
                tool.handle(
                    PendingImageGenerationToolEvent(
                    callId = "call_1",
                    arguments = ImageGenToolArguments(prompt = "draw"),
                ),
                ),
            )
            val result = assertIs<StableImageGenerationResult.Success>(completed.result)
            val outputPath = Path(root, "session", "call_1.png")

            assertEquals(
                encodedImage,
                result.output.result,
            )
            assertEquals(
                "Generated images are saved to ${outputPath.parent} as $outputPath by default.\n" +
                    "If you need to use a generated image at another path, copy it and leave the original " +
                    "in place unless the user explicitly asks you to delete it.",
                result.output.outputHint,
            )
            assertContentEquals(bytes, SystemCoroutineFileSystem.readBytes(outputPath))
            assertEquals(outputPath.toString(), result.savedPath)
        } finally {
            deleteImageGenerationToolFiles(root)
        }
    }
}

private suspend fun deleteImageGenerationToolFiles(path: Path) {
    val metadata = SystemCoroutineFileSystem.metadataOrNull(path) ?: return
    if (metadata.isDirectory) {
        SystemCoroutineFileSystem.list(path).forEach { child ->
            deleteImageGenerationToolFiles(child)
        }
    }
    SystemCoroutineFileSystem.delete(path, mustExist = false)
}
