package io.github.stream29.kodex.tool.imagegeneration

import de.infix.testBalloon.framework.core.testSuite
import io.github.stream29.kodex.utils.kotlinxiocoroutines.SystemCoroutineFileSystem
import kotlinx.io.files.Path
import kotlinx.io.files.SystemTemporaryDirectory
import kotlin.io.encoding.Base64
import kotlin.random.Random
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals

val generatedImageArtifactsTest by testSuite {
    test("persists generated bytes under sanitized session and call paths") {
        val root = Path(SystemTemporaryDirectory, "kodex-image-store-${Random.nextLong()}")
        val bytes = byteArrayOf(0x89.toByte(), 0x50, 0x4e, 0x47)
        try {
            val result = GeneratedImageOutput(Base64.encode(bytes)).persistGeneratedImage(
                outputDirectory = ImageGenerationTools.outputDirectory(root, "thread:/one"),
                callId = "call two",
            )
            val outputPath = Path(root, "generated_images", "thread__one", "call_two.png")

            assertContentEquals(bytes, SystemCoroutineFileSystem.readBytes(outputPath))
            assertEquals(
                "Generated images are saved to ${outputPath.parent} as $outputPath by default.\n" +
                    "If you need to use a generated image at another path, copy it and leave the original " +
                    "in place unless the user explicitly asks you to delete it.",
                result.outputHint,
            )
        } finally {
            deleteGeneratedImageTestFiles(root)
        }
    }
}

private suspend fun deleteGeneratedImageTestFiles(path: Path) {
    val metadata = SystemCoroutineFileSystem.metadataOrNull(path) ?: return
    if (metadata.isDirectory) {
        SystemCoroutineFileSystem.list(path).forEach { child ->
            deleteGeneratedImageTestFiles(child)
        }
    }
    SystemCoroutineFileSystem.delete(path, mustExist = false)
}
