package io.github.stream29.codex.lite.tool.imagegeneration

import de.infix.testBalloon.framework.core.testSuite

import io.github.stream29.codex.lite.openai.FunctionCallOutputBody
import io.github.stream29.codex.lite.openai.FunctionCallOutputContentItem
import io.github.stream29.codex.lite.openai.ImageData
import io.github.stream29.codex.lite.openai.ImageDetail
import io.github.stream29.codex.lite.openai.ImageResponse
import io.github.stream29.codex.lite.openai.OpenAiResult
import io.github.stream29.codex.lite.openai.ResponseItem
import io.github.stream29.codex.lite.openai.jsoncodec.OpenAiJsonCodec
import io.github.stream29.codex.lite.openai.ResponsesApiNamespace
import io.github.stream29.codex.lite.openai.client.test.mockOpenAiClient
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue



private val json = OpenAiJsonCodec

val imageGenerationToolsTest by testSuite {
    test("spec declares image gen namespace tool") {
        val namespace = ImageGenerationTools.spec as ResponsesApiNamespace
        val encoded = json.parseToJsonElement(json.encodeToString(namespace)).jsonObject
        val tool = encoded.getValue("tools").jsonArray.single().jsonObject

        assertEquals(ImageGenNamespace, encoded["name"]?.toString()?.trim('"'))
        assertEquals(ImageGenToolName, tool["name"]?.toString()?.trim('"'))
        assertFalse("output_schema" in tool)
    }

    test("parameters expose prompt and edit inputs") {
        val namespace = ImageGenerationTools.spec as ResponsesApiNamespace
        val tool = namespace.tools.single()
        val encoded = json.parseToJsonElement(json.encodeToString(tool)).jsonObject
        val properties = encoded
            .getValue("parameters")
            .jsonObject
            .getValue("properties")
            .jsonObject

        assertTrue("prompt" in properties)
        assertTrue("referenced_image_paths" in properties)
        assertTrue("num_last_images_to_include" in properties)
    }

    test("generated bytes are returned as image content with the persisted path hint") {
        val tool = ImageGenerationTools.createTool(
            client = ImageGenerationToolClient(
                client = mockOpenAiClient {
                    generateImage {
                        OpenAiResult.Success(
                            ImageResponse(
                                created = 1,
                                data = listOf(ImageData("BASE64")),
                            ),
                        )
                    }
                },
            ),
            transformOutput = { callId, output ->
                output.copy(outputHint = "saved $callId")
            },
        )

        val result = tool.handle(
            ResponseItem.FunctionCall(
                callId = "call_1",
                namespace = ImageGenNamespace,
                name = ImageGenToolName,
                arguments = """{"prompt":"draw"}""",
            ),
        ) as ResponseItem.FunctionCallOutput
        val content = (result.output.body as FunctionCallOutputBody.ContentItems).items

        assertEquals(
            FunctionCallOutputContentItem.InputImage(
                imageUrl = "data:image/png;base64,BASE64",
                detail = ImageDetail.High,
            ),
            content[0],
        )
        assertEquals(FunctionCallOutputContentItem.InputText("saved call_1"), content[1])
        assertEquals(true, result.output.success)
    }
}
